<?php
// accounting hardwired data for hopestats script

$accounting['2007']['01']['impairment_loss_allowance']='-';
$accounting['2007']['01']['total_expenses']=2411614;
$accounting['2007']['01']['annual_inflation_rate']='4.3%';
$accounting['2007']['01']['adj_inflation_portfolio_devaluation']='-';
$accounting['2007']['01']['cash_estimate']=1255754;
$accounting['2007']['01']['adj_inflation_cash_devaluation']='-';
$accounting['2007']['01']['total_adjustment']='-';
$accounting['2007']['01']['operational_self_sufficiency']='68%';
$accounting['2007']['01']['finantial_self_sufficiency']='54.3%';
$accounting['2007']['01']['loan_officers_count']=31;
$accounting['2007']['01']['total_staff_count']=52;

$accounting['2007']['01']['cost_dollar_lent']=0.10;
$accounting['2007']['01']['cost_loan_disbursed']=250.66;
$accounting['2007']['01']['volunteer_count']='-';
$accounting['2007']['01']['children_count']='-';
$accounting['2007']['01']['exchange_rate']='-';
// --------------------------------------------

$accounting['2007']['02']['impairment_loss_allowance']='-';
$accounting['2007']['02']['total_expenses']=1547377;
$accounting['2007']['02']['annual_inflation_rate']='4.3%';
$accounting['2007']['02']['adj_inflation_portfolio_devaluation']='-';
$accounting['2007']['02']['cash_estimate']=2150554;
$accounting['2007']['02']['adj_inflation_cash_devaluation']='-';
$accounting['2007']['02']['total_adjustment']='-';
$accounting['2007']['02']['operational_self_sufficiency']='71%';
$accounting['2007']['02']['finantial_self_sufficiency']='60%';
$accounting['2007']['02']['loan_officers_count']=31;
$accounting['2007']['02']['total_staff_count']=52;

$accounting['2007']['02']['cost_dollar_lent']=0.10;
$accounting['2007']['02']['cost_loan_disbursed']=152.71;
$accounting['2007']['02']['volunteer_count']='-';
$accounting['2007']['02']['children_count']='-';
$accounting['2007']['02']['exchange_rate']='-';
// -----------------------------------------------

$accounting['2007']['03']['impairment_loss_allowance']='-';
$accounting['2007']['03']['total_expenses']=2024151;
$accounting['2007']['03']['annual_inflation_rate']='4.3%';
$accounting['2007']['03']['adj_inflation_portfolio_devaluation']='-';
$accounting['2007']['03']['cash_estimate']=586223;
$accounting['2007']['03']['adj_inflation_cash_devaluation']='-';
$accounting['2007']['03']['total_adjustment']='-';
$accounting['2007']['03']['operational_self_sufficiency']='72%';
$accounting['2007']['03']['finantial_self_sufficiency']='54.3%';
$accounting['2007']['03']['loan_officers_count']=31;
$accounting['2007']['03']['total_staff_count']=52;

$accounting['2007']['03']['cost_dollar_lent']=0.10;
$accounting['2007']['03']['cost_loan_disbursed']=188.80;
$accounting['2007']['03']['volunteer_count']='-';
$accounting['2007']['03']['children_count']='-';
$accounting['2007']['03']['exchange_rate']='-';
// -----------------------------------------------

$accounting['2007']['04']['impairment_loss_allowance']='-';
$accounting['2007']['04']['total_expenses']=2124998;
$accounting['2007']['04']['annual_inflation_rate']='4.3%';
$accounting['2007']['04']['adj_inflation_portfolio_devaluation']='-';
$accounting['2007']['04']['cash_estimate']=770000;
$accounting['2007']['04']['adj_inflation_cash_devaluation']='-';
$accounting['2007']['04']['total_adjustment']='-';
$accounting['2007']['04']['operational_self_sufficiency']='72%';
$accounting['2007']['04']['finantial_self_sufficiency']='63%';
$accounting['2007']['04']['loan_officers_count']=31;
$accounting['2007']['04']['total_staff_count']=52;

$accounting['2007']['04']['cost_dollar_lent']=0.10;
$accounting['2007']['04']['cost_loan_disbursed']=191.17;
$accounting['2007']['04']['volunteer_count']='-';
$accounting['2007']['04']['children_count']='-';
$accounting['2007']['04']['exchange_rate']='-';
//--------------------------------------------------

$accounting['2007']['05']['impairment_loss_allowance']='-';
$accounting['2007']['05']['total_expenses']=2151376;
$accounting['2007']['05']['annual_inflation_rate']='4.3%';
$accounting['2007']['05']['adj_inflation_portfolio_devaluation']='-';
$accounting['2007']['05']['cash_estimate']=750000;
$accounting['2007']['05']['adj_inflation_cash_devaluation']='-';
$accounting['2007']['05']['total_adjustment']='-';
$accounting['2007']['05']['operational_self_sufficiency']='75%';
$accounting['2007']['05']['finantial_self_sufficiency']='62%';
$accounting['2007']['05']['loan_officers_count']=31;
$accounting['2007']['05']['total_staff_count']=52;

$accounting['2007']['05']['cost_dollar_lent']=0.10;
$accounting['2007']['05']['cost_loan_disbursed']=185.94;
$accounting['2007']['05']['volunteer_count']='-';
$accounting['2007']['05']['children_count']='-';
$accounting['2007']['05']['exchange_rate']='-';
//---------------------------------------------------

$accounting['2007']['06']['impairment_loss_allowance']='-';
$accounting['2007']['06']['total_expenses']=1953360;
$accounting['2007']['06']['annual_inflation_rate']='4.3%';
$accounting['2007']['06']['adj_inflation_portfolio_devaluation']='-';
$accounting['2007']['06']['cash_estimate']=558800;
$accounting['2007']['06']['adj_inflation_cash_devaluation']='-';
$accounting['2007']['06']['total_adjustment']='-';
$accounting['2007']['06']['operational_self_sufficiency']='80%';
$accounting['2007']['06']['finantial_self_sufficiency']='64%';
$accounting['2007']['06']['loan_officers_count']=31;
$accounting['2007']['06']['total_staff_count']=52;

$accounting['2007']['06']['cost_dollar_lent']=0.10;
$accounting['2007']['06']['cost_loan_disbursed']=164.81;
$accounting['2007']['06']['volunteer_count']='-';
$accounting['2007']['06']['children_count']='-';
$accounting['2007']['06']['exchange_rate']='-';
//-----------------------------------------------------

$accounting['2007']['07']['impairment_loss_allowance']='-';
$accounting['2007']['07']['total_expenses']=2134160;
$accounting['2007']['07']['annual_inflation_rate']='4.3%';
$accounting['2007']['07']['adj_inflation_portfolio_devaluation']='-';
$accounting['2007']['07']['cash_estimate']=665000;
$accounting['2007']['07']['adj_inflation_cash_devaluation']='-';
$accounting['2007']['07']['total_adjustment']='-';
$accounting['2007']['07']['operational_self_sufficiency']='82%';
$accounting['2007']['07']['finantial_self_sufficiency']='67%';
$accounting['2007']['07']['loan_officers_count']=31;
$accounting['2007']['07']['total_staff_count']=52;

$accounting['2007']['07']['cost_dollar_lent']=0.10;
$accounting['2007']['07']['cost_loan_disbursed']=177.30;
$accounting['2007']['07']['volunteer_count']='-';
$accounting['2007']['07']['children_count']='-';
$accounting['2007']['07']['exchange_rate']='-';
//-------------------------------------------------------

$accounting['2007']['08']['impairment_loss_allowance']='-';
$accounting['2007']['08']['total_expenses']=2255223;
$accounting['2007']['08']['annual_inflation_rate']='4.3%';
$accounting['2007']['08']['adj_inflation_portfolio_devaluation']='-';
$accounting['2007']['08']['cash_estimate']=485225;
$accounting['2007']['08']['adj_inflation_cash_devaluation']='-';
$accounting['2007']['08']['total_adjustment']='-';
$accounting['2007']['08']['operational_self_sufficiency']='84%';
$accounting['2007']['08']['finantial_self_sufficiency']='67%';
$accounting['2007']['08']['loan_officers_count']=31;
$accounting['2007']['08']['total_staff_count']=52;

$accounting['2007']['08']['cost_dollar_lent']=0.10;
$accounting['2007']['08']['cost_loan_disbursed']=188.31;
$accounting['2007']['08']['volunteer_count']='-';
$accounting['2007']['08']['children_count']='-';
$accounting['2007']['08']['exchange_rate']='-';
//------------------------------------------------------

$accounting['2007']['09']['impairment_loss_allowance']='-';
$accounting['2007']['09']['total_expenses']=1975112;
$accounting['2007']['09']['annual_inflation_rate']='6.8%';
$accounting['2007']['09']['adj_inflation_portfolio_devaluation']='-';
$accounting['2007']['09']['cash_estimate']=485225;
$accounting['2007']['09']['adj_inflation_cash_devaluation']='-';
$accounting['2007']['09']['total_adjustment']='-';
$accounting['2007']['09']['operational_self_sufficiency']='71%';
$accounting['2007']['09']['finantial_self_sufficiency']='63%';
$accounting['2007']['09']['loan_officers_count']=31;
$accounting['2007']['09']['total_staff_count']=52;

$accounting['2007']['09']['cost_dollar_lent']=0.10;
$accounting['2007']['09']['cost_loan_disbursed']=1550;
$accounting['2007']['09']['volunteer_count']='-';
$accounting['2007']['09']['children_count']='-';
$accounting['2007']['09']['exchange_rate']='-';

?>